### ISSUE TITLE
bug widget not advancing on screen unlock a14

### ISSUE THREAD

**Issue by nutpantz** [jameshnsears/QuoteUnquote#302] opened 2024-06-21 17:18 UTC
Pixel 8 android 14 
My settings are
Next sequencal
Widget
Screen unlock

It is not advancing on screen unlock
I can advance it manually

I am using the newest Nova launcher.
It is set to allow background operation

The bug appears to be random.
As just after I posted this its now working again after testing it was not working.

**Comment by nutpantz** [comment] 2024-06-22 23:32
If I go into config and out it will advance when I unlock. I double checked it can run in background.
Allow setting timers and alarms is also set to on.

Also on pixel 6 a13
I'm sure I did not have this issue on my pixel 6 a12 a few months ago

**Comment by jameshnsears** [comment] 2024-06-23 16:46
Hi - thanks for reporting this. Which version of the app are you on?

I'm on the latest - 4.41.0 - and am not able to repeat this (at least just now on OneUI 6.1 on A14). 

Are both devices using Nova launcher?

**Comment by jameshnsears** [comment] 2024-06-23 17:02
Actually - after recycling the device the screen unlock doesn't work even though it's ticked. Going back into the config and then immediately back seems to fix things. But it's obviously better if a restart continues where things left off. This behavior might have nothing to do with your issue though!

I'll investigate and try and resolve the issue I just identified, as well as look around for yours, this week in 4.41.0

Once again, thanks for raising the issue :-)

**Comment by nutpantz** [comment] 2024-06-23 23:55
Yes I am on 4.41. It acts the same on android 14,13,9

**Comment by jameshnsears** [comment] 2024-06-24 17:15
Hi - the app works as intended (for notification on device unlock, after rebooting) on my reference development emulators (including A7 & A14). On my own personal device, A14, it does not.

I haven't noticed this behavior as I'm not using device unlock notifications + no one else has mentioned this issue. Though it does ring a distant bell!

My understanding of things is that this behavior is down to something called Doze. It's a part of Android that has been in development from A6 and is used to  manage battery. A reboot can affect app widgets in negative ways, especially those that use notifications. 

**The answer is to manually reinitialise the app widget so it can resume normality. What works for me - after a reboot - is to visit the Configuration Notifications screen, then tap the back button / gesture.**

Try this and let me know if it works for you.

I'll likely update the instructions with this information in the next release.

PS - I'll admit I haven't installed Nova Launcher. I've only used the stock OneUI 6.1 launcher.

**Comment by jameshnsears** [comment] 2024-06-26 06:05
Hi - out of interest I installed Nova launcher prime, from google play store, Set it as my default launcher; installed the widget with device unlock notification enabled.

I rebooted, and got the same behavior and resolution as I described earlier.

**Comment by jameshnsears** [comment] 2024-07-04 05:54
I'm closing this issue now as I can't repeat.

**Closed as completed by jameshnsears** 2024-07-04 05:54 UTC
Labels: question, 4.42.0
